root = ".."
tmp_dir = "tmp"

[build]
include_ext = ["go", "html"]
include_dir = ["frontend", "pkg", "frontend/templates"]
cmd = "go build -o ./tmp/main ./..."

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
